### ISSUE TITLE
not letting me select a txt file

### ISSUE THREAD

**Issue by DaniLmaxo** [rifteyy/lol-account-checker#1]
Hi, tl;dr when I do the create new list option it simply doesnt show my txt document as if its not on my desktop, any way to fix this?

**Comment by rifteyy** [comment]
Hey, the new list option creates a file in the directory you select with an extension .ockr
.ockr is used for all the Open Checker lists, as this allows me to associate the extension with start.bat, so you can just double-click the .ockr file and it will launch it (if you decide to select `Associate .OCKR files with start.bat (this will allow to open by doubleclicking .OCKR list)`).
