### ISSUE TITLE
Not letting me import combolists

### ISSUE THREAD

**Issue by NicolasAbrahamowicz** [rifteyy/lol-account-checker#2]
Hello sir, when I try to import a combo list, it doesn't even lets me select the Combolist, it just instantly checks nothing.

Also, it looks like LCU Tokens are not being obtained.

I would also recommend implementing proxy usage (like user:pass@ip:port).

One more thing, don't you have any problem with captchas?

**Comment by NicolasAbrahamowicz** [comment]
Nice job by the way, the tools looks really nice.

**Comment by NicolasAbrahamowicz** [comment]
https://github.com/user-attachments/assets/b75d7d6b-f561-4d34-80ee-f4051fae15ce

**Comment by rifteyy** [comment]
Problem solved on Discord.

As mentioned in Note 2 in program description, captchas have unfortunately patched the way to get original registration server, last password change date and creation date.

Proxy support won't be added, because you are running the file locally and exporting it manually.
